### PR TITLE
More complete CircularArray and fixed fps bug

### LINKED ISSUE #5: [bug] Wrong FPS and TPS calculation
**Describe the bug**

Title.

**To Reproduce**

1. Turned on Kami Blue FPS HUD
2. I turned on the FPS HUD and adjusted smooth lighting setting & GUI Scale setting for MC
3. Time travelled ass backwards into next week

**Expected behavior**

Don't time travel ass backwards into next week

**Debug info**

image

**Additional context / media**

LAMBDA CLIENT ON TOP SOON TM

### PR DESCRIPTION
**Pull request by Luna5ama**
Thanks who ever wrote the incomplete code for that collection

Fixed #5

### CODE REVIEW

**Comment by czho** [comment]
Based

File: src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/misc/TPS.kt [hunk 1]
```diff
@@ -11,24 +12,24 @@ internal object TPS : LabelHud(
...
-            if (avg == 0.00f) {
-                displayText.add("%.2f".format(0.00f), primaryColor)
+            if (avg == 0.0f) {
+                displayText.add("%.2f".format(0.0f), primaryColor)
             } else {
-                displayText.add("%.2f".format(1000 / avg), primaryColor)
+                displayText.add("%.2f".format(1000.0f / avg), primaryColor)
             }
 
-            displayText.add("mspt", secondaryColor)
```
Comment (Avanatiker) [inline src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/misc/TPS.kt:31]: why not ms per tick

**Review by Avanatiker — APPROVED** [review]
